### ISSUE TITLE
Multiple relations to same table

### ISSUE THREAD

**Issue by scripter-co** [linkyndy/remodel#21]
I'm trying to related one table (Asset) to another (Files) multiple times, the reason for this is that one Asset can have many files, but also have one primary file related to it. I'm unsure if it's possible with this is possible, but so far I've tried various things mentioned in the documents but nothing seems to pick up my settings.

Heres my model layout:

    class Asset(Model):
	    has_one = (('File', 'files', 'id', 'default_icon_file_id'),)
	    has_many = ('File',)

    class File(Model):
	    has_many = ('File',)
	    belongs_to = ('File', 'Asset',)

I then try and set it using:

    asset['default_icon_file_id'] = models.File.get('ID HERE')

or

    asset['default_icon_file'] = models.File.get('ID HERE')

but nothing gets picked up. Any pointers would be appreciated. I'll try get around to creating a PR for the readme

**Comment by linkyndy** [comment]
Hello,

You needn't use the expanded format to define `Asset has_one File`. Here's how I've defined your models:

```
>>> from remodel.models import Model
>>> from remodel.helpers import create_tables, create_indexes
>>> class Asset(Model):
...     has_one = ('File',)
...     has_many = ('File',)
... 
>>> class File(Model):
...     has_many = ('File',)
...     belongs_to = ('File', 'Asset')
... 
>>> create_tables()
>>> create_indexes()
```

I've created both a file and an asset, then I linked the file to the asset:

```
>>> file = File.create()
>>> asset = Asset.create()
>>> asset['file'] = file # you can use File.get('whatever') also
>>> file.fields.as_dict()
{'asset_id': u'62afc2cc-5e7a-4aaf-ac56-617cb88620ff', u'id': u'8260587e-6799-449a-bac8-dd73ccb40c6d'}
```

Afterwards, I've saved the two files:

```
>>> file.save()
>>> asset.save()
```

It worked as expected. Basically, when you create the above relations, you activate `asset['file']`, `asset['files']`, `file['files']`, `file['file']` and `file['asset']` (listed in the order of declaration, where `asset` and `file` are instances of their models).

Actually, your expanded declaration of the `has_one` relation is overwritten by the following one, since you specify `files` to be the accessor field for the relation, which is the same as the default accessor for the following relation. If you want to give it a custom name, choose something different for the second item in the tuple (but for the basic, simple case, I suggest you stick with the conventions). Also, as another side note, remodel is designed so that you don't have to use the `_id` fields; they're in the database for handling relations and that's it; remodel provides accessors for all relations so that your life becomes much easier :) .

Hope this helped you, otherwise feel free to ask for more details.

**Comment by scripter-co** [comment]
That's what I had originally, and what I'm testing with now. The problem is, if you do

    asset['files'].add(file1)
    asset['files'].add(file2)

and then do

    asset['file'] = file2

it wont always use `file2`, it'll pick the first out when ordered by `id` in `asc`.

--------

So in my case, I've got this:

    asset['file'] = models.File.get(form_element)
    print asset['file'].fields.as_dict()
    asset.save()

with the output as (i've just left the basic info):

    {u'asset_id': u'b049b65d-7795-44f9-8306-2857a0717999', u'id': u'e3345321-99da-40fe-948d-5237ec7621c9'}

this is exactly right, so I then go to check that this has been set by doing:

    print all_assets[0]['file'].fields.as_dict() # I currently only have one asset record, so I know it's `0`

this outputs:

    {u'asset_id': u'b049b65d-7795-44f9-8306-2857a0717999', u'id': u'd7d9567a-6da0-4656-89c6-23ae9baa187d'}

which is wrong (the ID of the file is wrong). Also, there's no field in my table for `file`, as seen here:

![screen shot 2015-04-10 at 09 49 35](https://cloud.githubusercontent.com/assets/1334111/7084612/f1d11672-df66-11e4-9608-e065eea01337.png)

Here's the gist or the full, relevant sections: 
Save method: https://gist.github.com/scripter-co/307d2fd4c78e96c95ca0#file-gistfile1-txt-L13
Models: https://gist.github.com/scripter-co/c64fb047b885d3f96ed1
Index method: https://gist.github.com/scripter-co/69ef11c41c36fd14318a#file-gistfile1-txt-L6

**Comment by linkyndy** [comment]
OK, I think I see which is the problem. If you declare your models like above:

```
>>> from remodel.models import Model
>>> from remodel.helpers import create_tables, create_indexes
>>> class Asset(Model):
...     has_one = ('File',)
...     has_many = ('File',)
... 
>>> class File(Model):
...     has_many = ('File',)
...     belongs_to = ('File', 'Asset')
... 
>>> create_tables()
>>> create_indexes()
```

it tries to create two `asset_id` fields on the `File` model, which obviously leads to ambiguity when using this field. In this case, you could indeed use the tuple declaration for the relations, something like:

```
>>> from remodel.models import Model
>>> from remodel.helpers import create_tables, create_indexes
>>> class Asset(Model):
...     has_one = (('File', 'master_file', 'id', 'master_asset_id'),)
...     has_many = ('File',)
... 
>>> class File(Model):
...     has_many = ('File',)
...     belongs_to = ('File', ('Asset', 'master_asset', 'master_asset_id', 'id'), 'Asset')
... 
>>> create_tables()
>>> create_indexes()
```

This clearly separates the relations to the same model. You could then do:

```
>>> a = Asset.create(name='asset')
>>> mf = File.create(name='master_file')
>>> a.update(master_file=mf)
>>> mf.save() # !! 1-to-1 relations must be manually saved (like in Django)
>>> print Asset.get(name='asset').fields.as_dict()
{u'id': u'720eddfe-04be-439a-9654-15b88199654e', u'name': u'asset'}
>>> print File.get(name='master_file').fields.as_dict() # Master file has been linked
{u'id': u'48efeb2c-25d8-4f4f-a4d1-0df967b399fc', u'master_asset_id': u'720eddfe-04be-439a-9654-15b88199654e', u'name': u'master_file'}
>>> f1 = File.create(name='file1')
>>> f2 = File.create(name='file2')
>>> a['files'] = [f1, f2]
>>> a['files'].add(mf)
>>> list(a['files'].all()) # We can see f1, f2, as well as the master file, all correctly linked
[<File: 7fd396ee-d632-42b6-991c-93e9834a156f>, <File: 48efeb2c-25d8-4f4f-a4d1-0df967b399fc>, <File: f3580d74-f9c1-4425-a0d7-6fc3b980492e>]
```

Tell me whether the above works for you. I've tested myself and it yields the correct behavior.

**Comment by scripter-co** [comment]
Thanks for the info, that worked as expected, although I actually swapped round the owning side so that asset holds the `master_file_id`, not the file (that way I don't have to worry about removing the `master_asset_id` when updating it. Thanks for taking the time out to explain that.

**Comment by linkyndy** [comment]
I am glad it helped. Don't hesitate to ask anything if unclear or make any suggestion on how to make remodel better :)
