### ISSUE TITLE
KeyError: 'changes' when saving the same object consecutively

### ISSUE THREAD

**Issue by linkyndy** [linkyndy/remodel#23]
Recently, a bug occurs when trying to perform a consecutive save on an object that has the **same** fields:

```python
>>> user = User(...)
>>> user.save()
>>> user.save()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 260, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 263, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 260, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 431, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 521, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/src/app/instasong/resources/user.py", line 21, in put
    user.save()
  File "/usr/local/lib/python2.7/site-packages/remodel/models.py", line 89, in save
    self.fields.__dict__ = result['changes'][0]['new_val']
KeyError: 'changes'
```

This issue seems to happen since RethinkDB 2.0, when their API changed a bit. Instead of returning a `changes` array each time for an operation that receives `return_values=True` as an argument, now the `changes` array is returned only when actual changes have been made. Hence, this affects remodel when trying to perform `save()` consecutively on an object, without changing any of its fields.

There's an ongoing discussion at rethinkdb/rethinkdb#4068; I'll wait for a conclusion there before making changes to remodel. This shouldn't affect vital parts of your workflow with remodel since it's not common to just call `save()` multiple times on the same object.

Also, as it's current state, remodel doesn't _thoroughly_ support RethinkDB 2.0. There might be other issues as well. If that would be the case, I'll make a new release addressing those issues and fully supporting RethinkDB 2.0.

As always, if you have a special case or need regarding this issue, please comment and we'll figure it out.

P.S.: We should make sure to include a test with the above scenario in order for remodel to be more future proof.

**Comment by bahadir** [comment]
Hi,

Are you going to release a new version with this patch? I'm looking forward to have this workaround without messing with requirements.txt :)

**Comment by linkyndy** [comment]
Yes, I am, but currently I am waiting for both a conclusion regarding the RethinkDB issue and my pull request on the wercker box.

If nothing happens until Tuesday, I will make a release.

**Comment by linkyndy** [comment]
OK, I've released [remodel v0.4.1](https://github.com/linkyndy/remodel/releases/tag/v0.4.1) (grab it while it's hot!)

I'll keep this issue open in order to track changes from RethinkDB on this issue and to restore to the original wercker box after it gets updated.

**Comment by bahadir** [comment]
Thank you very much.

Keep up the great work!

**Comment by linkyndy** [comment]
[remodel v0.4.2](https://github.com/linkyndy/remodel/releases/tag/v0.4.2) is out now, implementing `return_changes='always'`, as introduced with RethinkDB 2.0.2. This issue is now closed.

**Comment by Gesias** [comment]
Great work btw, encountered this issue and found a ticket on it here. Just starting to get into this again and thought I should add a corner case for documentation. 
If one has a one to many relation like in the docs here and adds a save after the operation on line 2 this is also triggered.

    romania = Country.create(name='Romania')
    romania['cities'].add(City(name='Timisoara'), City(name='Bucharest'))
    romania.save() # Crash as it was saved already in the line before and no new changes to romania
    print romania['cities'].count() # prints 2

I just happened to run into it out of the habit of explicitly saving models which is not needed here as the add takes care of it.

**Comment by linkyndy** [comment]
And it fails throwing the error described in the issue? I cannot test right now, but it should be solved with the latest versions of RethinkDB and remodel. Can you confirm you have the latest versions (2.0.2 and 0.4.2)? If so, I'll check tonight to see where's the problem.

**Comment by Gesias** [comment]
It does, I checked and got 
remodel==0.4.2
rethinkdb==2.0.0-2 

the server is running on 2.0.1 actually, but 2.0.2 was released just 2 weeks ago which was after this ticket was created? It´s no hurry however.

**Comment by linkyndy** [comment]
You should update the RethinkDB server as well, not only the Python driver. Tell me whether it works after you have the time to check.

**Comment by Gesias** [comment]
I will check and get back, thanks for the swift response!

**Comment by Gesias** [comment]
It works as supposed now, sorry for bothering you mate!

**Comment by linkyndy** [comment]
No problem, glad it's alright! Closing the issue. Feel free to reopen it if something pop up.
