### ISSUE TITLE
Filter by function

### ISSUE THREAD

**Issue by NamPNQ** [linkyndy/remodel#28]
I think need make edit something https://github.com/linkyndy/remodel/blob/master/remodel/object_handler.py#L43 to allow filter by function

**Comment by linkyndy** [comment]
Currently `filter` only works with dicts. I have in mind a total refactor of the entire document retrieval process, and almost for sure I'll add the possibility to filter using a a `lambda`, as it's definitely very useful. Thanks for reporting this and stay close as new releases will come! :)

**Comment by NamPNQ** [comment]
So cool +1

**Comment by Gesias** [comment]
Agreed, very nice!

Vänliga hälsningar,
Klas

**Comment by NamPNQ** [comment]
Hi @linkyndy, is have update info about this isuse?

**Comment by linkyndy** [comment]
Although I have the best intentions, time isn't quite on my side lately, and also I started migrating to other languages so Python isn't my "tool" of choice at the moment. I'm trying to do my best; I plan to release this 0.5.0, fix some more bugs and release a stable 1.0.0, after which probably I'll have to step aside and just review what contributors bring to this project. Unfortunately, I can't predict an accurate date when all these things will happen. I can just promise I'll try to deliver.

**Comment by NamPNQ** [comment]
Tks you for reply

I think it is enought :dancer: 

![image](https://cloud.githubusercontent.com/assets/2740696/10263701/cf154752-6a21-11e5-86b9-5e629dc3b606.png)

**Comment by linkyndy** [comment]
A little late, but this has just been merged! Thanks @NamPNQ for opening this up!
