### ISSUE TITLE
Can we use it with tornado, like motorengine for mongoDB?

### ISSUE THREAD

**Issue by devlounge** [linkyndy/remodel#35]
Hi,

I was wondering if we can use it natively with Tornado in async mode, the same way we can do with motorengine, for example, assuming we have a User model:
user = User(....)
yield user.save()

Thank you in advance

**Comment by linkyndy** [comment]
I honestly don't know. I haven't tested anything alike with remodel, so I cannot tell you. If you can give it a try and post the results, I would be more than happy. Probably it won't work as expected, so pull requests are warmly welcome!

**Comment by linkyndy** [comment]
Closing this one for now. Feel free to reopen if you have more to add!
