### ISSUE TITLE
Support for secondary indexes

### ISSUE THREAD

**Issue by thedrow** [linkyndy/remodel#37]
Am I missing something or is it just not supported?

**Comment by linkyndy** [comment]
No, currently secondary indexes are not supported by remodel. I started this library with simplicity in mind, meaning that I've only implemented the _vital_ things.

If you have plans of adding support for them, I would be more than happy to help.

**Comment by linkyndy** [comment]
Closing this one, for now. If you wish to start working on this, I would be happy to help!
