### ISSUE TITLE
Question about custom class methods

### ISSUE THREAD

**Issue by SkiftCreative** [linkyndy/remodel#42]
I was reading through the readme file, and was curious about why we are creating custom class methods with the usage below

```
from remodel.object_handler import ObjectHandler, ObjectSet

class TripObjectHandler(ObjectHandler):
    def in_europe(self):
        return ObjectSet(self, self.query.filter({'continent': 'Europe'}))

class Trip(Model):
    object_handler = TripObjectHandler

Trip.create(continent='Europe', city='Paris')
Trip.create(continent='Asia', city='Shanghai')
Trip.create(continent='Europe', city='Dublin')
print len(Trip.in_europe()) # prints 2
```

It seems to me that it seems counter-intuitive compared to making it liks so:

```
class Trip(Model):
    @classmethod
    def in_europe(self):
        return self.query.filter({'continent': 'Europe'})

Trip.create(continent='Europe', city='Paris')
Trip.create(continent='Asia', city='Shanghai')
Trip.create(continent='Europe', city='Dublin')
print len(Trip.in_europe()) # prints 2
```

I am not saying you are doing it wrong, I am just curious why it wasn't done that way as it seems much more intuitive. I am sure theres something I don't know about yet as I am just starting to use remodel.

**Comment by linkyndy** [comment]
There are several reasons why `ObjectHandler` exists. It keeps the concerns separated, and doesn't let the `Model` class deal with both instance methods (i.e. for objects) and class methods. This keeps things modular and also allow you to easily extend object handlers to your own desire. You want to swap the default object handler and use something of your own? Simple, just assign your custom object handler class as:

```python
class Trip(Model):
    object_handler = TripObjectHandler
```

and you're good to go. If these were class methods, it would've been harder and a lot more _unintuitive_ to swap/extend them.

It's the same design decision as with the `FieldHandler`. I could've integrated it directly in the `Model` class, but that would've coupled classes too much.

To be easier for you to grasp this `ObjectHandler`, think of Django's [Managers](https://docs.djangoproject.com/en/1.9/topics/db/managers/).

Remodel's simplicity lies not only within it's interface, but also within how its code is structured.

**Comment by SkiftCreative** [comment]
Ok thanks, that does clear it up some. I was just curious for the reasoning. Thanks.
