### ISSUE TITLE
Async support for tornado/asynio.

### ISSUE THREAD

**Issue by v3ss0n** [linkyndy/remodel#45]
Rethinkdb work best with async frameworks as it have very cool async features. Currenly remodel is not using async driver.
Any plan to support async ?

**Comment by linkyndy** [comment]
This would be a very neat feature for remodel to support. Unfortunately, I have little to no time to big features to remodel, so any help (via a Pull Request) is much appreciated!

**Comment by linkyndy** [comment]
Going to close this. If you have time to implement such a feature, I would be more than glad to merged it in! 🙌
