### ISSUE TITLE
Custom table name

### ISSUE THREAD

**Issue by arwema** [linkyndy/remodel#47]
Is it possible to pass arbitrary table name instead of the defaults pluralized class name? Useful on existing tables auto-generated by horizon

**Comment by arwema** [comment]
The idea I have is to have _table property that when it exists it overwrites the plurarize function.

**Comment by linkyndy** [comment]
It addresses the same problem as #41, basically.

Since there is a lot of traction with this issue, I am inclined to agree having such an option. However, time is not on my side lately, so if you're willing to submit a pull request, I would gladly merge it.
