### ISSUE TITLE
How to select database for models to persist?

### ISSUE THREAD

**Issue by catroot** [linkyndy/remodel#49]
I didn't find how to set db the models operates to.
Is there a way to do it? Or i can supply an existing connection for db queries?

**Comment by linkyndy** [comment]
It seems this must have slipped from the documentation. I will add it as soon as I have some more time. Until then, Ryan Paul has done a great job with his [blog post](http://rethinkdb.com/blog/remodel/) about remodel:

```python
import remodel.connection

remodel.connection.pool.configure(db="fleet")
```

You can check all the accepted arguments [here](https://github.com/linkyndy/remodel/blob/master/remodel/connection.py#L14).

Hope this answered your question. Will leave this open until I add the missing docs.

**Comment by catroot** [comment]
Thank you.

**Comment by linkyndy** [comment]
I've updated both the wiki and the README with this. Thanks for spotting this!
