### ISSUE TITLE
Improve compatibility of __contains__ @line 149 in models.py

### ISSUE THREAD

**Issue by catroot** [linkyndy/remodel#52]
There a some incompatibility of checking several keys against fields names:

``` python
        Products = Code['pack']['value']['products'].all()
        products=[{'id':x['id'], 'name': x['name']} for x in Products if ('id', 'name') in x]
```

>  File "/home/proj3/venv-3.5/lib/python3.5/site-packages/remodel/models.py", line 149, in __ contains__
>     return hasattr(self.fields, item)
> TypeError: hasattr(): attribute name must be string

Need to make check for iterables for keys, returning `True` if all of them in place.

**Comment by catroot** [comment]
For me. fix is the something like this:
```python
    def __contains__(self, item):
        if not isinstance(item, str):
            res=True
            for i in item:
                res=hasattr(self.fields, i)
                print("checking", i)
        else:
            res=hasattr(self.fields, item)
        return res

```

**Comment by linkyndy** [comment]
A model's interface was designed to resemble `dict`s as much as possible. In that sense, checking for more than one field on an object is more than Python's `dict` interface. Also, you example may assume you are checking whether a specific tuple is inside an object, which may lead to ambiguity. In the end, I don't think this should be implemented in remodel's interface. I will close this issue for now, but feel free to reopen it if you have more to add!
