### ISSUE TITLE
Model filtering should not use params that are empty strings ("") or None

### ISSUE THREAD

**Issue by fnrcum** [linkyndy/remodel#57]
So I have been messing around with remodel and I can say I like it but my biggest issue is filtering objects based on multiple POSSIBLE params.

For example i have a starship with name, category, id ....... , and want to filter by just the id, i use `Starship.filter(id=.....)` but for example if i want to filter by the other 2 params not knowing which was supplied i have to do a larger number of conditional statements (or at least i couldn't find another way) as if i try the following:
`Starship.filter(category=category if category is not None else "", name=name if name is not None else "")` it will obviously return nothing if one of them is an empty string.

Is there a way to filter by POSSIBLE params without using custom Model queries or am I stuck using those?

**Comment by linkyndy** [comment]
Apologies for the late response. The [`filter`](https://github.com/linkyndy/remodel/blob/master/remodel/object_handler.py#L43) method on a model mostly wraps RethinkDB's [`filter`](https://rethinkdb.com/api/python/filter/). You can always provide an expanded dict as an argument, like:

```python
d = { 'id': 12, 'category': 'foo' }
Starship.filter(**d)
```

This way you can dynamically provide filters to your model, optionally prepared beforehand as you wish.

Let me know if this helped!

**Comment by linkyndy** [comment]
I would assume it did, and I'm closing this issue. If you have more questions, feel free to reopen!
