### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by smewp** [linkyndy/remodel#7]

**Comment by smewp** [comment]
I've worked on it and many tests are passing in python 3.4 but currently have 7 failures in test_models.SaveTests and 16 similarly related failures in the test_related.py group.  

Repo is at https://github.com/smewp/remodel_py3

Current problem causing all failures is in models.py and I'm not having much success fixing it. Issue code is below:

    result = (r.table(self._table).get(id_).replace(r.row
                        .without(list(r.row.keys()).difference(list(fields_dict.keys())))
                        .merge(fields_dict), return_changes=True).run())

Pics:
![2015-01-10_12-34-05](https://cloud.githubusercontent.com/assets/526707/5690462/62fa9690-98c5-11e4-9ecf-82ae2290c235.jpg)
![2015-01-10_12-43-53](https://cloud.githubusercontent.com/assets/526707/5690474/7e7b7ba4-98c6-11e4-9f6e-94d6d128fe08.jpg)

**Comment by linkyndy** [comment]
It looks as if it doesn't like something with how the query is being built (specifically, the `merge` part). From what I've seen, the Python driver for RethinkDB is compatible with Python 3, so I find a bit weird that error.

Still, it's possible that arguments should be fed some other way, or even the query should be constructed in a different manner. I'll take a look the moment I'll have some spare time (very busy at the moment, sorry).

Thanks for helping with Python 3 support, @smewp!

**Comment by smewp** [comment]
Actually the change required to the query was minimal. Below solution:
result = (r.table(self._table).get(id_).replace(r.row
                        .without(r.row.keys().difference(list(fields_dict.keys())))
                        .merge(fields_dict), return_changes=True).run())

All current tests now pass on 2.7.8 and 3.4.2.  Thanks for putting this library together.  I know you are still going through revision but I look forward to using it now with my py3 project.

**Comment by linkyndy** [comment]
Wow, you actually did it! Congrats and thank you :) Will merge your pull request (#9) after we finish the discussions on it.

GJ ;)

**Comment by linkyndy** [comment]
remodel v0.3.0 is now on PyPI and has Python 3 support! Grab it while it's still hot :wink: 

Thanks again @smewp!

**Comment by joeldrapper** [comment]
Thanks everyone who worked on this!
